# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.22

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/venturf/Documents/CompositeCrypto/composite-provider

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/venturf/Documents/CompositeCrypto/composite-provider

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target test
test:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running tests..."
	/usr/bin/ctest --force-new-ctest-process $(ARGS)
.PHONY : test

# Special rule for the target test
test/fast: test
.PHONY : test/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components
.PHONY : list_install_components/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/venturf/Documents/CompositeCrypto/composite-provider/CMakeFiles /home/venturf/Documents/CompositeCrypto/composite-provider//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/venturf/Documents/CompositeCrypto/composite-provider/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named composite

# Build rule for target.
composite: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 composite
.PHONY : composite

# fast build rule for target.
composite/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/composite.dir/build.make CMakeFiles/composite.dir/build
.PHONY : composite/fast

#=============================================================================
# Target rules for targets named test_provider

# Build rule for target.
test_provider: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_provider
.PHONY : test_provider

# fast build rule for target.
test_provider/fast:
	$(MAKE) $(MAKESILENT) -f tests/CMakeFiles/test_provider.dir/build.make tests/CMakeFiles/test_provider.dir/build
.PHONY : test_provider/fast

#=============================================================================
# Target rules for targets named test_encoding

# Build rule for target.
test_encoding: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_encoding
.PHONY : test_encoding

# fast build rule for target.
test_encoding/fast:
	$(MAKE) $(MAKESILENT) -f tests/CMakeFiles/test_encoding.dir/build.make tests/CMakeFiles/test_encoding.dir/build
.PHONY : test_encoding/fast

#=============================================================================
# Target rules for targets named test_keygen_sig

# Build rule for target.
test_keygen_sig: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_keygen_sig
.PHONY : test_keygen_sig

# fast build rule for target.
test_keygen_sig/fast:
	$(MAKE) $(MAKESILENT) -f tests/CMakeFiles/test_keygen_sig.dir/build.make tests/CMakeFiles/test_keygen_sig.dir/build
.PHONY : test_keygen_sig/fast

#=============================================================================
# Target rules for targets named test_evp_keygen

# Build rule for target.
test_evp_keygen: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_evp_keygen
.PHONY : test_evp_keygen

# fast build rule for target.
test_evp_keygen/fast:
	$(MAKE) $(MAKESILENT) -f tests/CMakeFiles/test_evp_keygen.dir/build.make tests/CMakeFiles/test_evp_keygen.dir/build
.PHONY : test_evp_keygen/fast

#=============================================================================
# Target rules for targets named test_sign_verify

# Build rule for target.
test_sign_verify: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_sign_verify
.PHONY : test_sign_verify

# fast build rule for target.
test_sign_verify/fast:
	$(MAKE) $(MAKESILENT) -f tests/CMakeFiles/test_sign_verify.dir/build.make tests/CMakeFiles/test_sign_verify.dir/build
.PHONY : test_sign_verify/fast

#=============================================================================
# Target rules for targets named test_oid_registration

# Build rule for target.
test_oid_registration: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_oid_registration
.PHONY : test_oid_registration

# fast build rule for target.
test_oid_registration/fast:
	$(MAKE) $(MAKESILENT) -f tests/CMakeFiles/test_oid_registration.dir/build.make tests/CMakeFiles/test_oid_registration.dir/build
.PHONY : test_oid_registration/fast

src/composite_decoder.o: src/composite_decoder.c.o
.PHONY : src/composite_decoder.o

# target to build an object file
src/composite_decoder.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/composite.dir/build.make CMakeFiles/composite.dir/src/composite_decoder.c.o
.PHONY : src/composite_decoder.c.o

src/composite_decoder.i: src/composite_decoder.c.i
.PHONY : src/composite_decoder.i

# target to preprocess a source file
src/composite_decoder.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/composite.dir/build.make CMakeFiles/composite.dir/src/composite_decoder.c.i
.PHONY : src/composite_decoder.c.i

src/composite_decoder.s: src/composite_decoder.c.s
.PHONY : src/composite_decoder.s

# target to generate assembly for a file
src/composite_decoder.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/composite.dir/build.make CMakeFiles/composite.dir/src/composite_decoder.c.s
.PHONY : src/composite_decoder.c.s

src/composite_encoder.o: src/composite_encoder.c.o
.PHONY : src/composite_encoder.o

# target to build an object file
src/composite_encoder.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/composite.dir/build.make CMakeFiles/composite.dir/src/composite_encoder.c.o
.PHONY : src/composite_encoder.c.o

src/composite_encoder.i: src/composite_encoder.c.i
.PHONY : src/composite_encoder.i

# target to preprocess a source file
src/composite_encoder.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/composite.dir/build.make CMakeFiles/composite.dir/src/composite_encoder.c.i
.PHONY : src/composite_encoder.c.i

src/composite_encoder.s: src/composite_encoder.c.s
.PHONY : src/composite_encoder.s

# target to generate assembly for a file
src/composite_encoder.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/composite.dir/build.make CMakeFiles/composite.dir/src/composite_encoder.c.s
.PHONY : src/composite_encoder.c.s

src/composite_kem.o: src/composite_kem.c.o
.PHONY : src/composite_kem.o

# target to build an object file
src/composite_kem.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/composite.dir/build.make CMakeFiles/composite.dir/src/composite_kem.c.o
.PHONY : src/composite_kem.c.o

src/composite_kem.i: src/composite_kem.c.i
.PHONY : src/composite_kem.i

# target to preprocess a source file
src/composite_kem.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/composite.dir/build.make CMakeFiles/composite.dir/src/composite_kem.c.i
.PHONY : src/composite_kem.c.i

src/composite_kem.s: src/composite_kem.c.s
.PHONY : src/composite_kem.s

# target to generate assembly for a file
src/composite_kem.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/composite.dir/build.make CMakeFiles/composite.dir/src/composite_kem.c.s
.PHONY : src/composite_kem.c.s

src/composite_keymgmt.o: src/composite_keymgmt.c.o
.PHONY : src/composite_keymgmt.o

# target to build an object file
src/composite_keymgmt.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/composite.dir/build.make CMakeFiles/composite.dir/src/composite_keymgmt.c.o
.PHONY : src/composite_keymgmt.c.o

src/composite_keymgmt.i: src/composite_keymgmt.c.i
.PHONY : src/composite_keymgmt.i

# target to preprocess a source file
src/composite_keymgmt.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/composite.dir/build.make CMakeFiles/composite.dir/src/composite_keymgmt.c.i
.PHONY : src/composite_keymgmt.c.i

src/composite_keymgmt.s: src/composite_keymgmt.c.s
.PHONY : src/composite_keymgmt.s

# target to generate assembly for a file
src/composite_keymgmt.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/composite.dir/build.make CMakeFiles/composite.dir/src/composite_keymgmt.c.s
.PHONY : src/composite_keymgmt.c.s

src/composite_keys.o: src/composite_keys.c.o
.PHONY : src/composite_keys.o

# target to build an object file
src/composite_keys.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/composite.dir/build.make CMakeFiles/composite.dir/src/composite_keys.c.o
.PHONY : src/composite_keys.c.o

src/composite_keys.i: src/composite_keys.c.i
.PHONY : src/composite_keys.i

# target to preprocess a source file
src/composite_keys.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/composite.dir/build.make CMakeFiles/composite.dir/src/composite_keys.c.i
.PHONY : src/composite_keys.c.i

src/composite_keys.s: src/composite_keys.c.s
.PHONY : src/composite_keys.s

# target to generate assembly for a file
src/composite_keys.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/composite.dir/build.make CMakeFiles/composite.dir/src/composite_keys.c.s
.PHONY : src/composite_keys.c.s

src/composite_sig.o: src/composite_sig.c.o
.PHONY : src/composite_sig.o

# target to build an object file
src/composite_sig.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/composite.dir/build.make CMakeFiles/composite.dir/src/composite_sig.c.o
.PHONY : src/composite_sig.c.o

src/composite_sig.i: src/composite_sig.c.i
.PHONY : src/composite_sig.i

# target to preprocess a source file
src/composite_sig.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/composite.dir/build.make CMakeFiles/composite.dir/src/composite_sig.c.i
.PHONY : src/composite_sig.c.i

src/composite_sig.s: src/composite_sig.c.s
.PHONY : src/composite_sig.s

# target to generate assembly for a file
src/composite_sig.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/composite.dir/build.make CMakeFiles/composite.dir/src/composite_sig.c.s
.PHONY : src/composite_sig.c.s

src/composite_sig_encoding.o: src/composite_sig_encoding.c.o
.PHONY : src/composite_sig_encoding.o

# target to build an object file
src/composite_sig_encoding.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/composite.dir/build.make CMakeFiles/composite.dir/src/composite_sig_encoding.c.o
.PHONY : src/composite_sig_encoding.c.o

src/composite_sig_encoding.i: src/composite_sig_encoding.c.i
.PHONY : src/composite_sig_encoding.i

# target to preprocess a source file
src/composite_sig_encoding.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/composite.dir/build.make CMakeFiles/composite.dir/src/composite_sig_encoding.c.i
.PHONY : src/composite_sig_encoding.c.i

src/composite_sig_encoding.s: src/composite_sig_encoding.c.s
.PHONY : src/composite_sig_encoding.s

# target to generate assembly for a file
src/composite_sig_encoding.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/composite.dir/build.make CMakeFiles/composite.dir/src/composite_sig_encoding.c.s
.PHONY : src/composite_sig_encoding.c.s

src/composite_sig_key.o: src/composite_sig_key.c.o
.PHONY : src/composite_sig_key.o

# target to build an object file
src/composite_sig_key.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/composite.dir/build.make CMakeFiles/composite.dir/src/composite_sig_key.c.o
.PHONY : src/composite_sig_key.c.o

src/composite_sig_key.i: src/composite_sig_key.c.i
.PHONY : src/composite_sig_key.i

# target to preprocess a source file
src/composite_sig_key.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/composite.dir/build.make CMakeFiles/composite.dir/src/composite_sig_key.c.i
.PHONY : src/composite_sig_key.c.i

src/composite_sig_key.s: src/composite_sig_key.c.s
.PHONY : src/composite_sig_key.s

# target to generate assembly for a file
src/composite_sig_key.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/composite.dir/build.make CMakeFiles/composite.dir/src/composite_sig_key.c.s
.PHONY : src/composite_sig_key.c.s

src/mldsa_composite.o: src/mldsa_composite.c.o
.PHONY : src/mldsa_composite.o

# target to build an object file
src/mldsa_composite.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/composite.dir/build.make CMakeFiles/composite.dir/src/mldsa_composite.c.o
.PHONY : src/mldsa_composite.c.o

src/mldsa_composite.i: src/mldsa_composite.c.i
.PHONY : src/mldsa_composite.i

# target to preprocess a source file
src/mldsa_composite.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/composite.dir/build.make CMakeFiles/composite.dir/src/mldsa_composite.c.i
.PHONY : src/mldsa_composite.c.i

src/mldsa_composite.s: src/mldsa_composite.c.s
.PHONY : src/mldsa_composite.s

# target to generate assembly for a file
src/mldsa_composite.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/composite.dir/build.make CMakeFiles/composite.dir/src/mldsa_composite.c.s
.PHONY : src/mldsa_composite.c.s

src/mlkem_composite.o: src/mlkem_composite.c.o
.PHONY : src/mlkem_composite.o

# target to build an object file
src/mlkem_composite.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/composite.dir/build.make CMakeFiles/composite.dir/src/mlkem_composite.c.o
.PHONY : src/mlkem_composite.c.o

src/mlkem_composite.i: src/mlkem_composite.c.i
.PHONY : src/mlkem_composite.i

# target to preprocess a source file
src/mlkem_composite.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/composite.dir/build.make CMakeFiles/composite.dir/src/mlkem_composite.c.i
.PHONY : src/mlkem_composite.c.i

src/mlkem_composite.s: src/mlkem_composite.c.s
.PHONY : src/mlkem_composite.s

# target to generate assembly for a file
src/mlkem_composite.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/composite.dir/build.make CMakeFiles/composite.dir/src/mlkem_composite.c.s
.PHONY : src/mlkem_composite.c.s

src/provider.o: src/provider.c.o
.PHONY : src/provider.o

# target to build an object file
src/provider.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/composite.dir/build.make CMakeFiles/composite.dir/src/provider.c.o
.PHONY : src/provider.c.o

src/provider.i: src/provider.c.i
.PHONY : src/provider.i

# target to preprocess a source file
src/provider.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/composite.dir/build.make CMakeFiles/composite.dir/src/provider.c.i
.PHONY : src/provider.c.i

src/provider.s: src/provider.c.s
.PHONY : src/provider.s

# target to generate assembly for a file
src/provider.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/composite.dir/build.make CMakeFiles/composite.dir/src/provider.c.s
.PHONY : src/provider.c.s

src/provider_ctx.o: src/provider_ctx.c.o
.PHONY : src/provider_ctx.o

# target to build an object file
src/provider_ctx.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/composite.dir/build.make CMakeFiles/composite.dir/src/provider_ctx.c.o
.PHONY : src/provider_ctx.c.o

src/provider_ctx.i: src/provider_ctx.c.i
.PHONY : src/provider_ctx.i

# target to preprocess a source file
src/provider_ctx.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/composite.dir/build.make CMakeFiles/composite.dir/src/provider_ctx.c.i
.PHONY : src/provider_ctx.c.i

src/provider_ctx.s: src/provider_ctx.c.s
.PHONY : src/provider_ctx.s

# target to generate assembly for a file
src/provider_ctx.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/composite.dir/build.make CMakeFiles/composite.dir/src/provider_ctx.c.s
.PHONY : src/provider_ctx.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... install"
	@echo "... install/local"
	@echo "... install/strip"
	@echo "... list_install_components"
	@echo "... rebuild_cache"
	@echo "... test"
	@echo "... composite"
	@echo "... test_encoding"
	@echo "... test_evp_keygen"
	@echo "... test_keygen_sig"
	@echo "... test_oid_registration"
	@echo "... test_provider"
	@echo "... test_sign_verify"
	@echo "... src/composite_decoder.o"
	@echo "... src/composite_decoder.i"
	@echo "... src/composite_decoder.s"
	@echo "... src/composite_encoder.o"
	@echo "... src/composite_encoder.i"
	@echo "... src/composite_encoder.s"
	@echo "... src/composite_kem.o"
	@echo "... src/composite_kem.i"
	@echo "... src/composite_kem.s"
	@echo "... src/composite_keymgmt.o"
	@echo "... src/composite_keymgmt.i"
	@echo "... src/composite_keymgmt.s"
	@echo "... src/composite_keys.o"
	@echo "... src/composite_keys.i"
	@echo "... src/composite_keys.s"
	@echo "... src/composite_sig.o"
	@echo "... src/composite_sig.i"
	@echo "... src/composite_sig.s"
	@echo "... src/composite_sig_encoding.o"
	@echo "... src/composite_sig_encoding.i"
	@echo "... src/composite_sig_encoding.s"
	@echo "... src/composite_sig_key.o"
	@echo "... src/composite_sig_key.i"
	@echo "... src/composite_sig_key.s"
	@echo "... src/mldsa_composite.o"
	@echo "... src/mldsa_composite.i"
	@echo "... src/mldsa_composite.s"
	@echo "... src/mlkem_composite.o"
	@echo "... src/mlkem_composite.i"
	@echo "... src/mlkem_composite.s"
	@echo "... src/provider.o"
	@echo "... src/provider.i"
	@echo "... src/provider.s"
	@echo "... src/provider_ctx.o"
	@echo "... src/provider_ctx.i"
	@echo "... src/provider_ctx.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

