#ifndef _MLDSA_COMPOSITE_H
#define _MLDSA_COMPOSITE_H

#include "compat.h"
#include "composite_provider.h"

#include <openssl/core_names.h>

BEGIN_C_DECLS

                    // ==============
                    // KEM operations
                    // ==============
EXTERN_DECLARE_KEM_DISPATCH_TABLE(mlkem768, rsa2048)
EXTERN_DECLARE_KEM_DISPATCH_TABLE(mlkem768, rsa3072)
EXTERN_DECLARE_KEM_DISPATCH_TABLE(mlkem768, rsa4096)
EXTERN_DECLARE_KEM_DISPATCH_TABLE(mlkem768, x25519)
EXTERN_DECLARE_KEM_DISPATCH_TABLE(mlkem768, ecdh_p256)
EXTERN_DECLARE_KEM_DISPATCH_TABLE(mlkem768, ecdh_p384)
EXTERN_DECLARE_KEM_DISPATCH_TABLE(mlkem768, ecdh_brainpool256r1)
EXTERN_DECLARE_KEM_DISPATCH_TABLE(mlkem1024, rsa3072)
EXTERN_DECLARE_KEM_DISPATCH_TABLE(mlkem1024, ecdh_p384)
EXTERN_DECLARE_KEM_DISPATCH_TABLE(mlkem1024, ecdh_brainpool384r1)
EXTERN_DECLARE_KEM_DISPATCH_TABLE(mlkem1024, x448)
EXTERN_DECLARE_KEM_DISPATCH_TABLE(mlkem1024, ecdh_p521)

END_C_DECLS

#endif /* _MLDSA_COMPOSITE_H */
